### ISSUE TITLE
Mention in README that jupyter lab should be installed / show starting up

### ISSUE THREAD

**Issue by NickleDave** [edublancas/scipy-2022#1]
I wasn't able to run after `pip install -r requirements.txt` in the set up, even though `python check.py` gave me the thumbs up -- I think this is because I don't have a system-wide JupyterLab install? I just did `pip install jupyterlab` to fix this

Might be worth stating that's needed -- if I'm not wrong -- and walking through starting up JupyterLab if you want to reach totally newbies + ppl that are not already working in JupyterLab a lot

**Comment by edublancas** [comment]
yes, I realized that `jupyterlab` was missing from the `requirements.txt`, I just added it. thanks for the heads up!
